db:
    container_name: tracker_db
    image: postgres:13.2
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_PASSWORD=samplepass
      - POSTGRES_USER=tracker_user