# Generated by Django 3.2.9 on 2021-12-09 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_auto_20211203_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='balancechange',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='balancechange',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.method'),
        ),
    ]
