# Generated by Django 3.2.9 on 2022-03-17 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0004_rename_balancechange_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('vendor', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.category')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
