# Generated by Django 3.2.9 on 2022-03-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_transactionpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpreset',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.method'),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='vendor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
