# Generated by Django 3.2.9 on 2022-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20220317_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpreset',
            name='isExpense',
            field=models.BooleanField(null=True),
        ),
    ]
