# Generated by Django 3.2.9 on 2022-03-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_transactionpreset_isexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionpreset',
            name='isExpense',
        ),
    ]
