# Generated by Django 3.2.9 on 2022-03-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_transactionpreset_isexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpreset',
            name='isExpense',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
