# Generated by Django 3.2.9 on 2022-03-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_transactionpreset_isexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpreset',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.method'),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpreset',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
