# Generated by Django 3.2.9 on 2022-03-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20220321_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionpreset',
            name='date',
        ),
    ]
