# Generated by Django 3.2.9 on 2022-04-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_method_iconclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
